all:
	g++ -std=c++17 -o graph_build_flathm graph_build_flat_hm.cpp -O3
	g++ -std=c++17 -o graph_build_stdum graph_build_std_um.cpp -O3

.PHONY: clean
clean:
	rm -f graph_build_flathm graph_build_stdum
